### PR TITLE
Renamed package names so they won't conflict with each other.

### PR DESCRIPTION
**Pull request by MauroHorie**

### CODE REVIEW

**Comment by skidson** [comment]
Hmm, guessing these conflict with the old SDK? I'd rather use just .oauth rather than .oauth.auth then

**Comment by MauroHorie** [comment]
Yes, sdk.oauth now is the package name. The additional auth is the folder where the files are located so they are not at the root.

**Comment by skidson** [comment]
Any reason why they wouldn't be at the root? I just find the .oauth.auth name redundant

**Comment by MauroHorie** [comment]
I'm ok either way. But I didn't have a reason to remove the auth folder since you initially set it up with it.

**Comment by skidson** [comment]
Yea I would just refactor the whole package to "io.moj.mobile.android.sdk.oauth" to avoid the conflict, keeps it more concise (it's already horrendously long with all that mobile.android. stuff :P)

**Pull request merged**
