### PR TITLE
Added request model for POST /v2/mojios

### PR DESCRIPTION
**Pull request by skidson**
Tagged as build 0.0.14

### CODE REVIEW

**Comment by sureshven** [comment]
Quick general SDK qustion - any reason to not make SDK models immutable (create and get only)?

**Comment by skidson** [comment]
I do agree always immutable unless there's a reason otherwise - in this case there's a couple reasons:
1. We don't know what our clients want to do with our models. An example I can think of is they pull a model out of a database, use a setter to update a value, and then save it back (and maybe they have a job that syncs the database with the REST API asynchronously). One of the golden rules on Android is to avoid "new" whenever possible to save memory - allowing the use of setters here helps them in this case.
2. With a truly RESTful API, the entity you PUT or POST should ideally be the same structure as one you  would receive from a GET call. This means the majority of the request objects should simply be the models themselves. With that being the case, setters are required as the alternative would be Builder objects for every model (involving yet another object being created just to be thrown away after build()) or constructors with ~30 arguments (e.g. the Vehicle model).

--> Typing out that second point is actually making me think maybe instead of a ClaimMojioRequest object at all I should just be using a Mojio object for which I set the IMEI, e.g.
`Mojio request = new Mojio();
request.setIMEI("imei");
App.getMojioApi().claimMojio(request).enqueue(callback);`

What are your thoughts on that? On one hand it's encouraging reuse of our models and a RESTful architecture, but on the other makes it less clear what parameters are required if I were a developer using the SDK and not familiar with the REST documentation (as the ClaimMojioRequest makes this clear with its constructor).

**Comment by sureshven** [comment]
The 'new' issue is definitely an anachronism of using a GC'd language but in this case there doesn't seem to be a common scenario where a developer would use the SDK in such a manner as to generate lots of objects.

As far as REST - well that's always good for a debate since most implementations don't follow the letter of the law but I get your point (PATCH works here). Things like vehicles, trips, and other time series data could be seen as immutable since they should never change.

**Comment by sureshven** [comment]
You can go ahead and merge these commits.

**Pull request merged**
